### ISSUE TITLE
Missing transformer part in the code?

### ISSUE THREAD

**Issue by zzzxxxttt** [Jiaolong/trajectory-prediction#2]
Hi, I did a quick look through the code, but could not find the transformer part in the model structure, is this repo the full implementation of your paper?

**Comment by Jiaolong** [comment]
Hi, thanks for your interest in our work. Because the paper has not been submitted, there might be some modifications. We will make a complete version with transformer part as soon as the results are fixed.

**Comment by zzzxxxttt** [comment]
Got it, thanks for your reply and looking forward to your further release!

**Comment by Jiaolong** [comment]
The transformer code has been added. :)

**Comment by zzzxxxttt** [comment]
Thanks for the notification, really appreciate your opensource!
